apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/smarman85/argoapps
    path: apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argoapps
